name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent
      - name: Run unit tests
        run: yarn test
